Identifiable error
proximax-storage/proximax-utils-go pull request #1
Opened 2019-01-30 07:14 UTC by MickScorsese

Made MultiPartHttpClient unexported
Added IdentifiableError type
Made RestClient converts response to error when status code equals 400 or 500

2019-01-31 11:00 UTC, otsybizov commented on net/restclient.go
> +func handleResponse(resp *http.Response, dto interface{}) (*http.Response, error) {
Why return the response? The caller already has it.

2019-02-01 13:53 UTC, otsybizov approved these changes

2019-02-01 14:48 UTC, alvin-reyes requested changes
merge to development branch first then merge to master.

2019-02-04 09:29 UTC, Wondertan approved these changes

2019-02-04 09:29 UTC, merged